services:
  - type: web
    name: gitinsure-api
    env: docker
    plan: free
    repo: https://github.com/Priyanshu7275/guidewire-devtrails-university-hackathon
    branch: main
    # Build from repo root; set Docker context explicitly to project folder
    dockerfilePath: gitinsure/Dockerfile
    dockerContext: gitinsure
    autoDeploy: true
    envVars:
      - key: OPENWEATHERMAP_API_KEY
        value: "ed2d2f9dc32a0ebd848c9c4dc8c67dac"
