services:
  - type: web
    name: giginsure-api
    env: node
    plan: free
    repo: https://github.com/Priyanshu7275/guidewire-devtrails-university-hackathon
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: "mongodb+srv://giginsure_admin:88g2J9lVhORAQbDQ@giginsure.n3kfcyg.mongodb.net/giginsure?appName=giginsure"
      - key: JWT_SECRET
        value: "giginsure_prod_jwt_secret_9x2kL8mN4pQ7rT1vW6yA3bC5dE0fG"
      - key: OPENWEATHERMAP_API_KEY
        value: "ed2d2f9dc32a0ebd848c9c4dc8c67dac"
      - key: NEWS_API_KEY
        value: "7f7d4661828b453fad899849e9c3a0c1"
      - key: RAZORPAY_KEY_ID
        value: "rzp_test_placeholder"
      - key: RAZORPAY_KEY_SECRET
        value: "placeholder_secret"
      - key: ML_SERVICE_URL
        value: "http://localhost:5001"
      - key: ALLOWED_ORIGIN
        value: "https://priyanshuranjan.in"
